FROM mysql
#EXPOSE 3306


#docker create network handbook
#docker build -t mysql .
#docker run -it -p 3306:3306 --name mysql -e MYSQL_ROOT_PASSWORD=hien123 mysql
#docker run -it --name mysql -e MYSQL_ROOT_PASSWORD=hien123 mysql
#docker run -it --network handbook --name mysql -e MYSQL_ROOT_PASSWORD=hien123 mysql
#docker run -it --network handbook -v hanbook-db-datavolume:/var/lib/mysql  --name mysql -e MYSQL_ROOT_PASSWORD=hien123 mysql
#docker exec -it mysql bash
#mysql --user=root --password=###